var data=[];
var dataStr='1、picture1<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
2、picture2<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
3、picture3<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
4、picture4<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
5、picture5<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
6、picture6<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
7、picture7<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
8、picture8<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
9、picture9<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
10、picture10<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
11、picture11<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
12、picture12<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
13、picture13<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
14、picture14<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
15、picture15<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
16、picture16<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
17、picture17<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
18、picture18<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
19、picture19<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
<br>\
<br>\
20、picture20<br>\
<br>\
discription1<br>\
discription2<br>\
discription3<br>\
discription4<br>\
discription5<br>\
discription6<br>\
discription7<br>\
discription8<br>\
';
var d=dataStr.split('<br><br><br>');
for(var i=0;i<d.length;i++){
	var c=d[i].split('<br><br>');
	data.push({
		img: c[0].replace('、',' ')+'.jpg', //图片名称
		caption: c[0].split('、')[1],//c[0]1、picture1被分割成1 picture，返回数组的[1]的值为picture
		desc: c[1]
	});
	console.log(c[0].replace('、',' ')+'.jpg');
}

